const { chromium }=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1050},deviceScaleFactor:1});
 await page.addInitScript(() => localStorage.setItem('alvento_consent','denied'));
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const base=process.env.ARREARS_URL||'https://alvento.uk/case-studies/arrears/';
 await page.goto(base); await page.waitForFunction(()=>document.querySelector('#demo-status').textContent.includes('Mock ledger ready'));
 await page.evaluate(()=>document.fonts.ready);
 assert.equal(await page.locator('#ledger-rows tr').count(),7);
 await page.locator('[data-action=run]').click();
 await page.waitForFunction(()=>document.querySelector('#outbox').querySelectorAll('details').length===6);
 await page.locator('[data-action=run]').click();
 await page.waitForFunction(()=>document.querySelector('#demo-status').textContent.startsWith('0 new'));
 await page.locator('[data-action=pay]').click();
 await page.waitForFunction(()=>document.querySelector('#demo-status').textContent.startsWith('Signed test'));
 await page.locator('[data-action=pay]').click();
 await page.waitForFunction(()=>document.querySelector('#demo-status').textContent.startsWith('Repeated'));
 await page.locator('[data-action=advance]').click();
 await page.waitForFunction(()=>document.querySelector('#ledger-date').textContent==='11 Oct 2026');
 assert.equal(await page.locator('#outbox details').count(),10);
 await page.reload(); await page.waitForFunction(()=>document.querySelector('#ledger-date').textContent==='11 Oct 2026');
 assert.equal(await page.locator('#ledger-rows tr[data-status=paid]').count(),2);
 await page.locator('[data-action=reset]').click();
 await page.waitForFunction(()=>document.querySelector('#ledger-date').textContent==='04 Oct 2026');
 await page.addStyleTag({content:'nav{visibility:hidden}'});
 await page.locator('#ledger').screenshot({path:'/tmp/arrears-desktop.png'});
 await page.setViewportSize({width:390,height:844});
 await page.locator('#ledger').screenshot({path:'/tmp/arrears-mobile.png'});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 assert.equal(await page.locator('.ledger-scroll').evaluate(e=>e.scrollWidth>e.clientWidth),true);
 await page.locator('.ledger-scroll').evaluate(e=>e.scrollLeft=e.scrollWidth);
 await page.locator('[data-action=run]').click();
 await page.waitForFunction(()=>document.querySelector('#outbox').querySelectorAll('details').length===6);
 assert.deepEqual(errors,[]);
 console.log(JSON.stringify({result:'passed',viewports:[1440,390],workflow:'run, rerun, payment, replay, advance, refresh, reset',browserErrors:errors}));
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
